# -*- coding: utf-8 -*-
"""markdown_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awhah4en_y9194ZwWnDzP_JiCS7YD74r
"""

# This creates the file 'markdown_generator.py'

import json
import sys
import os

def write_node_to_markdown(node, file_handle, level=0):
    """
    A recursive function to walk the JSON and write
    to the Markdown file.
    """
    indent = "  " * level  # 2 spaces per indentation level

    # Get the main topic/topic
    topic = ""
    if "main_topic" in node:
        topic = node["main_topic"]
        file_handle.write(f"# {topic}\n\n") # H1 for main topic
    elif "topic" in node:
        topic = node["topic"]
        file_handle.write(f"{indent}* **{topic}**\n")

    # Get the details
    if "details" in node:
        # If there was a topic, indent the detail.
        # If no topic, just make it a bullet.
        detail_indent = indent if not topic else indent + "    "
        file_handle.write(f"{detail_indent}* {node['details']}\n")

    # Add a newline for spacing after a block
    if topic or "details" in node:
        file_handle.write("\n")

    # Recurse for all children
    if "children" in node and node["children"]:
        for child in node["children"]:
            # Recurse with an increased level
            write_node_to_markdown(child, file_handle, level + 1)

if __name__ == "__main__":
    # We expect 2 arguments: <input_json> and <output_markdown>
    if len(sys.argv) != 3:
        print("Usage: python markdown_generator.py <input_json_path> <output_md_path>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.exists(input_file):
        print(f"Error: Input file not found at {input_file}")
        sys.exit(1)

    try:
        # Read the JSON data
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Write the Markdown file
        with open(output_file, 'w', encoding='utf-8') as f:
            write_node_to_markdown(data, f)

        print(f"✅ Successfully generated {output_file}")

    except Exception as e:
        print(f"Error in markdown_generator: {e}")
        sys.exit(1)