# -*- coding: utf-8 -*-
"""mindmap_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6puZD5VhJdWIsFjP5Cs_g7EsnDvoQzo
"""

# This creates the file 'mindmap_generator.py'

import json
import sys
import os
import re

# We use the 'graphviz' Python library
# It's a "wrapper" that helps us use the Graphviz tool we installed
try:
    import graphviz
except ImportError:
    print("Error: The 'graphviz' Python library is not installed.")
    print("Please run: !pip install graphviz")
    sys.exit(1)

def clean_text(text):
    """Removes special characters that break Graphviz."""
    # Remove quotes, newlines, and limit length
    text = text.replace('"', '').replace("'", "").replace("\n", " ")
    return text[:100] # Limit node text to 100 chars

def add_nodes_to_graph(node, graph, parent_id=None):
    """
    A recursive function to walk the JSON and add
    nodes and edges to the Graphviz graph.
    """

    # Create a unique ID for the current node
    current_id = str(hash(id(node))) # Use object's hash for a unique ID

    # --- Get the text for the node ---
    label = ""
    if "main_topic" in node:
        label = node["main_topic"]
    elif "topic" in node:
        label = node["topic"]

    if "details" in node:
        # If there's a topic, add the detail on a new line
        if label:
            label += f"\n({clean_text(node['details'])})"
        else: # If there's *only* a detail
            label = clean_text(node['details'])

    if not label:
        label = "Unnamed Node"

    # Add the node to the graph
    graph.node(current_id, label=clean_text(label))

    # If this isn't the root node, draw an edge from its parent
    if parent_id:
        graph.edge(parent_id, current_id)

    # Recurse for all children
    if "children" in node and node["children"]:
        for child in node["children"]:
            add_nodes_to_graph(child, graph, parent_id=current_id)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python mindmap_generator.py <input_json_path> <output_png_path>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.exists(input_file):
        print(f"Error: Input file not found at {input_file}")
        sys.exit(1)

    try:
        # Read the JSON data
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Create a new Graphviz 'Digraph' (Directed Graph)
        dot = graphviz.Digraph(comment='Lecture Mind Map')
        dot.attr(rankdir='TB') # Top-to-Bottom layout
        dot.attr('node', shape='box', style='filled', color='skyblue')

        # Start the recursive process
        add_nodes_to_graph(data, dot)

        # Render the graph and save it as a PNG file
        # The 'format='png'' part is what creates the image
        dot.render(output_file.replace('.png', ''), format='png', cleanup=True)

        print(f"✅ Successfully generated {output_file}")

    except Exception as e:
        print(f"Error in mindmap_generator: {e}")
        sys.exit(1)