# -*- coding: utf-8 -*-
"""pdf_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZ3Us1KoYTffQV-6l-C9nNIaaZFWvI-n
"""

# This creates the file 'pdf_extractor.py'

import pymupdf  # The PyMuPDF library
import sys
import os

def extract_text_from_pdf(pdf_path, txt_output_path):
    """
    Opens a digital PDF, extracts all text, and saves it to a .txt file.
    """
    try:
        # Open the PDF file
        doc = pymupdf.open(pdf_path)

        full_text = ""
        # Loop through each page in the PDF
        for page_num in range(len(doc)):
            page = doc.load_page(page_num)
            full_text += page.get_text() # Get the digital text

        # Write the combined text to our output file
        with open(txt_output_path, 'w', encoding='utf-8') as f:
            f.write(full_text)

        print(f"✅ Successfully extracted text from '{pdf_path}' and saved to '{txt_output_path}'")

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1) # Exit with an error if something went wrong

# This part runs when we call the script from the command line
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python pdf_extractor.py <input_pdf_path> <output_txt_path>")
        sys.exit(1)

    pdf_path = sys.argv[1]
    txt_output_path = sys.argv[2]

    if not os.path.exists(pdf_path):
        print(f"Error: Input file not found at {pdf_path}")
        sys.exit(1)

    extract_text_from_pdf(pdf_path, txt_output_path)